backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/pages/novedades'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - { label: 'Post destacado', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Imágen destacada', name: 'featuredimage', widget: image }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
      - { label: 'Tags (Etiquetas)', name: 'tags', widget: 'list' }

  - name: 'paginas'
    label: 'Páginas'
    files:
      - file: 'src/pages/index.md'
        label: 'Home'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - { label: Título, name: title, widget: string }
          - { label: Imágen, name: image, widget: image }
          - { label: Encabezado, name: heading, widget: string }
          - { label: Bajada, name: subheading, widget: string }
          - {
              label: Campo principal,
              name: mainpitch,
              widget: object,
              fields: [{ label: Título, name: title, widget: string }, { label: Descripción, name: description, widget: text }],
            }
          - { label: Descripción, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Encabezado, name: heading, widget: string },
                  { label: Descripción, name: description, widget: text },
                  {
                    label: Anuncios,
                    name: blurbs,
                    widget: list,
                    fields: [{ label: Imágen, name: image, widget: image }, { label: Texto, name: text, widget: text }],
                  },
                ],
            }
          - {
              label: Principal,
              name: main,
              widget: object,
              fields:
                [
                  { label: Encabezado, name: heading, widget: string },
                  { label: Descripción, name: description, widget: text },
                  {
                    label: Imágen 1,
                    name: image1,
                    widget: object,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                  {
                    label: Imágen 2,
                    name: image2,
                    widget: object,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                  {
                    label: Imágen 3,
                    name: image3,
                    widget: object,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                ],
            }
      - file: 'src/pages/institucional/index.md'
        label: 'Institucional'
        name: 'institucional'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
      - file: 'src/pages/products/index.md'
        label: 'Products Page'
        name: 'products'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'product-page' }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }, { label: Text, name: text, widget: text }],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields: [{ label: Quote, name: quote, widget: string }, { label: Author, name: author, widget: string }],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        { label: Description, name: description, widget: string },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
